language: swift
osx_image: xcode10
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- bundle install
- cd SnapshotTests
- carthage update --platform iOS

script:
- cd ..
- fastlane test

after_failure:
- if [[ $TRAVIS_PULL_REQUEST_SLUG == "aol-public/OneMobileSDK-controls-ios" ]]; then . manage-diffs.sh; fi


after_success:
- if [[ $TRAVIS_PULL_REQUEST_SLUG == "aol-public/OneMobileSDK-controls-ios" ]]; then . manage-diffs.sh; fi
