os: osx
language: objective-c
osx_image: xcode10.1
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- bundle install
- cd SnapshotTests
- carthage update --platform iOS

script:
- cd ..
- bundle exec fastlane test
- bundle exec fastlane lint_current_podspec

after_failure:
- if [[ $TRAVIS_PULL_REQUEST_SLUG == "VerizonAdPlatforms/VerizonVideoPartnerSDK-controls-ios" ]]; then . manage-diffs.sh; fi

after_success:
- if [[ $TRAVIS_PULL_REQUEST_SLUG == "VerizonAdPlatforms/VerizonVideoPartnerSDK-controls-ios" ]]; then . manage-diffs.sh; fi
